// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskOTron.Api.Data;

#nullable disable

namespace TaskOTron.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913135616_AddBudgets")]
    partial class AddBudgets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BudgetItemSub", b =>
                {
                    b.Property<int>("BudgetItemsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoriesId")
                        .HasColumnType("TEXT");

                    b.HasKey("BudgetItemsId", "CategoriesId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("BudgetItemSub");
                });

            modelBuilder.Entity("TaskOTron.Api.Models.BankAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("TaskOTron.Api.Models.Budget", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("From")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("TaskOTron.Api.Models.BudgetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("BudgetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MainId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("MainId");

                    b.ToTable("BudgetItems");
                });

            modelBuilder.Entity("TaskOTron.Api.Models.Main", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mains");
                });

            modelBuilder.Entity("TaskOTron.Api.Models.SavedQuery", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SavedQueries");
                });

            modelBuilder.Entity("TaskOTron.Api.Models.Sub", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MainId");

                    b.ToTable("Subs");
                });

            modelBuilder.Entity("TaskOTron.Api.Models.TitleDefault", b =>
                {
                    b.Property<string>("NormalizedTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainId")
                        .HasColumnType("TEXT");

                    b.HasKey("NormalizedTitle");

                    b.HasIndex("MainId");

                    b.ToTable("TitleDefaults");
                });

            modelBuilder.Entity("TaskOTron.Api.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Done")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DoneAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Due")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("MainId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("TitleDefaultSub", b =>
                {
                    b.Property<string>("CategoriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleDefaultsNormalizedTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriesId", "TitleDefaultsNormalizedTitle");

                    b.HasIndex("TitleDefaultsNormalizedTitle");

                    b.ToTable("TitleDefaultSub");
                });

            modelBuilder.Entity("TodoSub", b =>
                {
                    b.Property<string>("CategoriesId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TodosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriesId", "TodosId");

                    b.HasIndex("TodosId");

                    b.ToTable("TodoSub");
                });

            modelBuilder.Entity("BudgetItemSub", b =>
                {
                    b.HasOne("TaskOTron.Api.Models.BudgetItem", null)
                        .WithMany()
                        .HasForeignKey("BudgetItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskOTron.Api.Models.Sub", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskOTron.Api.Models.BudgetItem", b =>
                {
                    b.HasOne("TaskOTron.Api.Models.Budget", "Budget")
                        .WithMany("Items")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskOTron.Api.Models.Main", "Main")
                        .WithMany()
                        .HasForeignKey("MainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Budget");

                    b.Navigation("Main");
                });

            modelBuilder.Entity("TaskOTron.Api.Models.Sub", b =>
                {
                    b.HasOne("TaskOTron.Api.Models.Main", "Main")
                        .WithMany("Subs")
                        .HasForeignKey("MainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Main");
                });

            modelBuilder.Entity("TaskOTron.Api.Models.TitleDefault", b =>
                {
                    b.HasOne("TaskOTron.Api.Models.Main", "Main")
                        .WithMany()
                        .HasForeignKey("MainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Main");
                });

            modelBuilder.Entity("TaskOTron.Api.Models.Todo", b =>
                {
                    b.HasOne("TaskOTron.Api.Models.BankAccount", "BankAccount")
                        .WithMany("Todos")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaskOTron.Api.Models.Main", "Main")
                        .WithMany()
                        .HasForeignKey("MainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BankAccount");

                    b.Navigation("Main");
                });

            modelBuilder.Entity("TitleDefaultSub", b =>
                {
                    b.HasOne("TaskOTron.Api.Models.Sub", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskOTron.Api.Models.TitleDefault", null)
                        .WithMany()
                        .HasForeignKey("TitleDefaultsNormalizedTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TodoSub", b =>
                {
                    b.HasOne("TaskOTron.Api.Models.Sub", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskOTron.Api.Models.Todo", null)
                        .WithMany()
                        .HasForeignKey("TodosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskOTron.Api.Models.BankAccount", b =>
                {
                    b.Navigation("Todos");
                });

            modelBuilder.Entity("TaskOTron.Api.Models.Budget", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TaskOTron.Api.Models.Main", b =>
                {
                    b.Navigation("Subs");
                });
#pragma warning restore 612, 618
        }
    }
}
